"""Added tables

Revision ID: 97764c51794e
Revises: 
Create Date: 2022-08-01 12:57:30.959651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97764c51794e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
