"""Added create date

Revision ID: 9d9759983082
Revises: 75c4299c0db8
Create Date: 2022-08-01 16:26:50.239951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9759983082'
down_revision = '75c4299c0db8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('basket_device', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('brand', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('category', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('category_brand', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('device', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('device_info', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('rating', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created')
    op.drop_column('rating', 'created')
    op.drop_column('device_info', 'created')
    op.drop_column('device', 'created')
    op.drop_column('category_brand', 'created')
    op.drop_column('category', 'created')
    op.drop_column('brand', 'created')
    op.drop_column('basket_device', 'created')
    op.drop_column('basket', 'created')
    # ### end Alembic commands ###
