"""Added tables 3

Revision ID: e263e4354f2d
Revises: bab0de825820
Create Date: 2022-08-01 13:16:16.361918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e263e4354f2d'
down_revision = 'bab0de825820'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
